### ISSUE TITLE
Broken css in impressionist

### ISSUE THREAD

**Issue by Fandekasp** [henrikingo/impressionist#16]
Hi Henrik.
I did another presentation with ingress.js this weekend, but I had to prepare the slides without using impressionist. That's because the css to make the presentation work on chrome was broken in impressionist.

You can check the presentation here: https://adrien.is/talks/20180224_kubernetes/#/overview
And see the related code here: https://github.com/Fandekasp/talks/tree/master/20180224_kubernetes

Screenshot:
![](https://i.imgur.com/uU9L18d.png)

Wondering if this could be easily fixed in impressionist's codebase. Or if you have suggestions for me to use css rules that work on both impressionist and chrome.

**Comment by henrikingo** [comment]
Hi Adrien

Your issues have to do with some things being larger in Electron than Chrome, causing some texts to reflow from their intended positions. I don't know why Electron doesn't match Chrome 1-for-1, but these things happed to me too. I even had to fix the original impress.js demo in a couple places.

The easiest one is the word "Kubernetes" on the title slide. For some reason the font is bigger, or possible the slide is narrower, and the word flows into 2 rows. Select the word and make the font smaller (or edit your css by hand) and it falls into place again.

The other problem seems to be your images on history_4, the CSS making them fit on the slide doesn't apply and they are all over the place.

I'm not aware that there's anything in particular I can do to fix these in impressionist itself. Possibly upgrading Electron version will help, or not. But in general, I currently don't expect every imaginable impress.js presentation to work in Impressionist. In fact, it will always be possible to do cooler things outside of impressionist than in it. (Markdown or relative positioning are some examples.)
