### ISSUE TITLE
Can't save project from template

### ISSUE THREAD

**Issue by asystat** [henrikingo/impressionist#24]
I love this tool, but for some reason I cannot save any changes I make with it. No error is thrown through the console. 
Neither the "save" or the "save as" buttons work in any way. 
Is there something I may be doing wrong?
Thanks

**Comment by henrikingo** [comment]
Can you add a bit more detail so I can try it: Which template did you use, and which changes did you try to do?

**Comment by henrikingo** [comment]
Ok, this was also reported by email and indeed Save was broken after I upgraded tinyMCE last year. I've now reverted back to the old version. Saving should work now. Please try again.

Will need to add more testing before upgrading anything again.
