### ISSUE TITLE
Can't open poject

### ISSUE THREAD

**Issue by Thatoo** [henrikingo/impressionist#25]
Hello,

After `npm start`, I click on open and I select one of the template, nothing happen.
After `npm start` I have the following message in the terminal

> \> impressionist@0.1.0 start /home/Thatoo/impressionist
> \> electron .
> 
> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

As soon as I click on "open", in the terminal, it says

> Gtk-Message: 11:59:39.281: GtkDialog mapped without a transient parent. This is discouraged.

What can I do?

Also, when I did `npm install`, I had these messages

> npm WARN deprecated mkdirp@0.3.2: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> loadDep:global-tunnel-ng  ▌ ╢███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> WARN engine global-agent@2.1.8: wanted: {"node":">=10.0"} (current: {"node":"8.1loadDep:serialize-error → ▌ ╢███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> WARN engine semver@7.3.2: wanted: {"node":">=10"} (current: {"node":"8.10.0","np

I'm working on Linux Mint 19.2.

I hope it helps. Thank you for your work.

**Comment by prabhatCH** [comment]
Same here. Get this as log on `npm start`
```
> impressionist@0.1.0 start /home/Thatoo/impressionist
> electron .
```
And a blank window opens up. Can't do anything else post that. 
I'm on macOS Catalina 10.15.4

**Comment by henrikingo** [comment]
@prabhatCH Do you have a File menu in your blank window? If yes, that's it. There is no nice start screen yet. You need to File -> Open a presentation (template) to get started.

@Thatoo Sorry for not responding earlier. I use Linux too (various Ubuntu/Kubuntu) and it works for me. Since I haven't had a Linux Mint installation available, I haven't had an opportunity to try to reproduce your report.

**Comment by prabhatCH** [comment]
@henrikingo Got it. Works. Thanks.
