### ISSUE TITLE
Pressing 'p' always opens a new Window

### ISSUE THREAD

**Issue by Tom-Julux** [henrikingo/impressionist#8]
This is unexpected behavior when editing code, where you need a <p>, or writing a word like 'impress'.

**Comment by Julisep** [comment]
I wanted to write < p >

**Comment by henrikingo** [comment]
Hi

Sorry it's been a bit quiet here. First I had notifications turned off in this repo. Once I realized that, I've seen this, but have been busy the past 7 months to merge my work in impress.js back upstream. But now I've finally worked through the issue queue in impress.js, and focusing on impressionist again.

Btw, thanks for filing this. The same issue was a problem for impress.js itself too, if a presentation would contain form fields. See https://github.com/impress/impress.js/issues/525
